<div id="printRelievingletter" class="modal-body"><div class="row printing"><div class="col-md-12"><div class="card card-primary card-outline"><div class="card-body box-profile"><table class="table table-condensed"><thead><td><img src="https://demo.microfincare.com/backend/system/public/storage/logo/ECyvrcjFA5WyPdVkBwB4Lr91FkM7y9sOTcq5p9Hx.png" height="100" width="100%"></td> <td class="text-center"><h4><strong>MICROMUNEEM MICROFINANCE SOFTWARE</strong> <br> <small>Address : AGRA, AGRA, Uttar Pradesh - 282010
                            <br>CIN : U65990UP2019PLC111111, Website - demo.microfincare.com, Mobile No - 9911551344, Email ID - vaishniltd@outlook.com
                            </small><br><br><strong>Relieving Letter</strong></h4></td> <td class="text-right"><div><svg class="vue-barcode-element" width="110px" height="87px" x="0px" y="0px" viewBox="0 0 110 87" xmlns="http://www.w3.org/2000/svg" version="1.1" style="transform: translate(0,0)"><rect x="0" y="0" width="110" height="87" style="fill:#ffffff;"></rect><g transform="translate(10, 10)" style="fill:#000000;"><rect x="0" y="0" width="2" height="45"></rect><rect x="3" y="0" width="1" height="45"></rect><rect x="6" y="0" width="1" height="45"></rect><rect x="11" y="0" width="1" height="45"></rect><rect x="13" y="0" width="1" height="45"></rect><rect x="17" y="0" width="2" height="45"></rect><rect x="22" y="0" width="1" height="45"></rect><rect x="24" y="0" width="3" height="45"></rect><rect x="28" y="0" width="2" height="45"></rect><rect x="33" y="0" width="1" height="45"></rect><rect x="35" y="0" width="3" height="45"></rect><rect x="39" y="0" width="4" height="45"></rect><rect x="44" y="0" width="2" height="45"></rect><rect x="49" y="0" width="1" height="45"></rect><rect x="51" y="0" width="3" height="45"></rect><rect x="55" y="0" width="2" height="45"></rect><rect x="59" y="0" width="3" height="45"></rect><rect x="64" y="0" width="1" height="45"></rect><rect x="66" y="0" width="1" height="45"></rect><rect x="68" y="0" width="1" height="45"></rect><rect x="72" y="0" width="4" height="45"></rect><rect x="77" y="0" width="2" height="45"></rect><rect x="82" y="0" width="3" height="45"></rect><rect x="86" y="0" width="1" height="45"></rect><rect x="88" y="0" width="2" height="45"></rect><text style="font: 20px monospace" text-anchor="middle" x="45" y="67">AM5018</text></g></svg><div style="display: none;">
                          Show this if the rendering fails.
                        </div></div></td></thead></table> <hr width="100%"> <table width="100%" class="table"><thead><td><b>
                          ANUJ RATHI <br> <i>RANJEET NAGAR,</i><br> <i>SRE,</i><i>Uttar Pradesh -</i> <i>247001</i><br></b></td> <td class="text-right">Branch: GAVDA <br>Date: 23-01-2025</td></thead></table> <p class="text-center text-bold">Relieving Letter</p> <p>Dear <b>ANUJ RATHI</b></p> <p>We are in receipt of your resignation dated 01-12-2024.<br>
                    We have accepted your resignation and as per company policy you will be relieved with effect from 31-01-2025</p> <p>We wish you all the best for your future endeavors.</p><br><br><br><br> <p>Thanking you</p><br><br><br><br> <p>Yours sincerely,<br>
                    Authorized Signatory<br>
                    MICROMUNEEM MICROFINANCE SOFTWARE
                  </p><br><br><br><br> <p> ANUJ RATHI<br> <b>Agent</b></p> <br><br></div></div></div></div></div>